## Задание 1. Создание и изменение массивов

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a*2
a[a > 10] = 0

print('Матрица с заменёнными элементами\n',  a)

Матрица с заменёнными элементами
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание 2. Работа с булевыми масками

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [18]:
a = np.random.randint(1, 100, 20)
print(a, '\n')

print('Элеметы, делящиеся нацело на пять: ', a[a%5 == 0], '\n')

a[a%5 == 0] = -1

print('Массив с заменёнными элементами: ', a)

[77 13 82  1 41 25 79 84 17 29 53 20 88 38 51 47 68  8 80 26] 

Элеметы, делящиеся нацело на пять:  [25 20 80] 

Массив с заменёнными элементами:  [77 13 82  1 41 -1 79 84 17 29 53 -1 88 38 51 47 68  8 -1 26]


## Задание 3. Объединение и разбиение массивов

Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.
+ Объедините эти массивы в один двумерный массив (по строкам).
+ Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты.

In [19]:
a = np.random.randint(0, 50, size = (1, 5))
a1 = np.random.randint(0, 50, size = (1, 5))

result = np.vstack((a, a1))

b = result[0, :]
b1 = result[1, :]
print('Рандомизированные массивы:\n', a, a1)
print('Объединённые массивы:\n', result)
print('Разделённые массивы:\n', b, b1)

Рандомизированные массивы:
 [[ 4 43 16 48 44]] [[ 5 41 18 36  9]]
Объединённые массивы:
 [[ 4 43 16 48 44]
 [ 5 41 18 36  9]]
Разделённые массивы:
 [ 4 43 16 48 44] [ 5 41 18 36  9]


## Задание 4. Генерация и работа с линейными последовательностями

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [20]:
mas = np.random.uniform(-10, 10, 50)
print(mas, '\n')

summ = sum(mas)
sum_poz = sum(mas[mas>0])
sum_neg = sum(mas[mas<0]) 

print('Сумма = ', summ)
print('Сумма положительных = ', sum_poz)
print('Сумма отрицательных = ', sum_neg)

[-6.85680194e+00  8.15418844e+00 -9.90993437e+00 -4.32413643e+00
  3.16471982e+00  8.90098882e+00 -5.53432642e+00 -1.92569062e+00
  5.20813804e+00  8.39811797e+00  6.43380732e+00 -7.56559873e+00
 -3.75719779e+00 -3.98990140e-01 -8.37942623e+00  9.11985757e+00
 -9.93230679e+00 -9.23114897e+00  4.97617021e+00  1.45546698e+00
 -2.23344387e-01  3.16128034e+00 -9.29940353e+00  6.38038506e+00
  9.78105519e-01  3.47998304e-01 -1.58728767e+00  3.93474447e+00
 -8.42224056e+00 -9.85327396e+00  6.82494678e+00  3.98115995e+00
 -1.70306445e+00 -1.77603088e+00 -7.70243908e+00  6.34004000e+00
  5.68195913e+00  6.14046299e+00 -2.14754825e+00 -4.12864946e+00
 -5.36877649e+00 -5.84975186e+00  1.32331266e+00  1.11763562e+00
  8.08659340e+00  7.92487137e+00 -3.41380004e+00 -5.91382551e+00
 -6.55464706e+00  4.31698185e-03] 

Сумма =  -23.720373851180703
Сумма положительных =  118.0392677491189
Сумма отрицательных =  -141.7596416002996


## Задание 5. Работа с диагональными и единичными матрицами

Создайте:
+ Единичную матрицу размером 4×4.
+ Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [25]:
a = np.eye(4)
m = [5, 10, 15, 20]
a1 = np.diag(m)

sum_el_a = np.sum(a)
sum_el_a1 = np.sum(a1)

print('Суммма  элементов матрицы a = ',sum_el_a) 
print('Суммма элементов матрицы а1 = ', sum_el_a1)

Суммма  элементов матрицы a =  4.0
Суммма элементов матрицы а1 =  50


## Задание 6. Создание и базовые операции с матрицами

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
+ Их сумму
+ Их разность
+ Их поэлементное произведение

In [27]:
a = np.random.randint(1, 20, size=(3, 3))  
a1 = np.random.randint(1, 20, size=(3, 3))  

print('Сумма матриц:\n',  a + a1)  
print('Разность матриц:\n', a - a1)  
print('Поэлементое произведение:\n',  a * a1)

Сумма матриц:
 [[13 29 36]
 [10 11 29]
 [16 20 12]]
Разность матриц:
 [[  7  -9   0]
 [  4   7   7]
 [-14  10  -6]]
Поэлементое произведение:
 [[ 30 190 324]
 [ 21  18 198]
 [ 15  75  27]]


## Задание 7. Умножение матриц

Создайте две матрицы NumPy:
+ Первую размером 2×3, заполненную случайными числами от 1 до 10.
+ Вторую размером 3×2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение (`@` или `np.dot`) и выведите результат.

In [28]:
matrix1 = np.random.randint(1, 10, size = (2, 3))
matrix2 = np.random.randint(1, 10, size = (3, 2))

print('Первая матрица:\n', matrix1)
print('Вторая матрица:\n', matrix2)
print('Результат матричного умножения:\n', np.dot(matrix1, matrix2))

Первая матрица:
 [[9 7 8]
 [2 1 4]]
Вторая матрица:
 [[9 8]
 [5 6]
 [6 6]]
Результат матричного умножения:
 [[164 162]
 [ 47  46]]


## Задание 8. Определитель и обратная матрица

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
+ Определитель этой матрицы
+ Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)

Используйте функции `np.linalg.det` и `np.linalg.inv`.

In [133]:
matrix = np.random.randint(1, 20, size=(3, 3))
det = np.linalg.det(matrix)

if det == 0:
    print('Матрица вырождена')
else:
    inv = np.linalg.inv(matrix)
    print('Определитель = ', det)
    print('Oбратная матрица:\n', inv)

Определитель =  -792.0000000000008
Oбратная матрица:
 [[-0.04040404  0.01010101  0.07070707]
 [-0.05555556  0.26388889 -0.02777778]
 [ 0.13131313 -0.28282828  0.02020202]]


## Задание 9. Транспонирование и след матрицы

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от
1 до 50. Выведите:
+ Исходную матрицу
+ Транспонированную матрицу
+ След матрицы (сумму элементов на главной диагонали)

Используйте `np.trace` для нахождения следа.

In [135]:
matrix = np.random.randint(1, 50, size = (4,4))
trace = np.trace(matrix)

print('Исходная матрица:\n', matrix)
print('Транспонированная матрица:\n', np.transpose(matrix))
print('След = ', trace)

Исходная матрица:
 [[11 44 15 31]
 [16 31 44  6]
 [40 48 45 43]
 [39 25 34 13]]
Транспонированная матрица:
 [[11 16 40 39]
 [44 31 48 25]
 [15 44 45 34]
 [31  6 43 13]]
След =  100


## Задание 10. Системы линейных уравнений 

Решите систему линейных уравнений вида:

\begin{cases} 
2x + 3y - z = 5 \\ 
4x - y + 2z = 6 \\ 
-3x + 5y + 4z = -2 
\end{cases}

Используйте матричное представление  Ax = B , где  A  – матрица коэффициентов, x  – вектор неизвестных,  B  – вектор правой части. Решите систему с помощью `np.linalg.solve` и выведите результат.

In [136]:
A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = [5, 6, -2]

solution = np.linalg.solve(A, B)

print(solution)

[1.63963964 0.57657658 0.00900901]


## Задание 11. Индивидуальное задание

19. **Аренда конференц-зала.** Организаторы мероприятия арендуют зал и делят стоимость между тремя группами участников: обычными, VIP и студентами. Билеты для студентов стоят в два раза дешевле обычных, а VIP-билеты — в 1.5 раза дороже обычных. Всего собрано 500 000 рублей, причем студентов было в два раза больше, чем обычных участников. Сколько билетов каждого типа продано?

Обозначим за **x** стоимость обычных билетов, тогда стоимость VIP-билетов будет составлять **1.5x**, а билетов  для студентов — **0.5x**.

Количество обычных участников обозначим за **n**, a VIP-участников — за **m**. Тогда количество студентов будет равно **2n**.

Составим уравнение:

$$x*n + 1.5*x*m + 0.5*x*2*n = 500 000$$

Получаем:

$$x*n + 1.5*x*m + x*n = 500 000$$
$$2xn + 1.5xm = 500 000$$

Данное уравнение, составленное, **согласно условиям задачи**, имеет 3 неизвестных и может иметь множество решений. 


Предположим, что VIP-участников в 2 раза меньше, чем обычных участников. Тогда **m = 0.5n**.
Получаем:

$$2xn + 1.5x*0.5n = 500 000$$
$$2xn + 0.75xn = 500 000$$
$$2.75xn = 500 000$$

Данное уравнение имеет 2 неизвестных и всё ещё имеет множество решений.

Предположим, что цена обычного билета известна и равна **x = 1000**.
Тогда:

$$2.75*1000*n = 500 000$$
$$n \approx 181$$
$$m = 0.5n = 0.5*181 \approx 90$$
$$ 2n = 2*181 = 362$$
Таким образом, **число обычных участников 181, студентов — 362, VIP-участников — 90**.

**Вывод**: в данном варианте невозможно привести задачу к построению системы линейных уравнений из-за отсутствия дополнительных условий.

30. **Рацион питания спортсмена.** Спортсмену необходимо потреблять 150 г белков, 70 г жиров и 300 г углеводов в день. Он может получать их из трех продуктов: яиц, куриного филе и овсянки. В 100 г яиц содержится 12 г белков, 10 г жиров и 1 г углеводов, в 100 г куриного филе — 25 г белков, 5 г жиров и 0 г углеводов, в 100 г овсянки — 10 г белков, 5 г жиров и 60 г углеводов. Сколько граммов каждого продукта ему нужно съесть в день?

Обозначим вес продуктов в граммах: вес яиц - **x**, вес куриного филе - **y**, вес овсянки - **z**.
Составим систему уравнений:

\begin{cases} 
12x + 25y + 10z = 15000 \\
10x + 5y + 5z = 7000 \\
x + 0y + 60z = 30000 \\
\end{cases}
Умножаем правые части уравнений на 100, потому что исходные данные даны на 100 г продукта

In [5]:
# решение матричным методом
A = np.array([[12,25,10], 
            [10, 5, 5], 
            [1, 0, 60]])
A_inv = np.linalg.inv(A) #обратная матрица
B = [15000, 7000, 30000]
X = np.dot(A_inv, B)
print('Решение матричным методом: ')
print(X[0], 'г яиц')
print(X[1], 'г куриного филе')
print(X[2], 'г овсянки')

# Решение методом крамера
det_A = np.linalg.det(A)
A1 = A.copy()
A2 = A.copy()
A3 = A.copy()
# Заменяем столбцы на вектор B

A1[:, 0] = B   
A2[:, 1] = B  
A3[:, 2] = B  
#Вычисляем определители новых матриц

det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)
# находим иксы

x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A

print('Решение методом Крамера: ')
print(x1, 'г яиц')
print(x2, 'г куриного филе')
print(x3, 'г овсянки')

#проверка третьим способом
print('Проверка методом linalg.solve(): ')
print(np.linalg.solve(A, B))

Решение матричным методом: 
331.1258278145694 г яиц
243.26710816777037 г куриного филе
494.4812362030906 г овсянки
Решение методом Крамера: 
331.1258278145693 г яиц
243.26710816777015 г куриного филе
494.4812362030897 г овсянки
Проверка методом linalg.solve(): 
[331.12582781 243.26710817 494.4812362 ]
